// Bundles YouTube.js + polyfills + the Tube bridge into one IIFE for JavaScriptCore.
import { build } from 'esbuild';
import { readFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(resolve(here, 'package.json'), 'utf8'));
const ytPkg = JSON.parse(readFileSync(resolve(here, 'node_modules/youtubei.js/package.json'), 'utf8'));
const bgPkg = JSON.parse(readFileSync(resolve(here, 'node_modules/bgutils-js/package.json'), 'utf8'));
const outfile = resolve(here, '../App/Resources/js/youtubei.bundle.js');
mkdirSync(dirname(outfile), { recursive: true });

const bundleVersion = `${pkg.version}+yt${ytPkg.version}`;

await build({
  entryPoints: [resolve(here, 'src/index.js')],
  outfile,
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['safari16'],
  keepNames: true,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  define: {
    global: 'globalThis',
    __BUNDLE_VERSION__: JSON.stringify(bundleVersion),
    __YOUTUBEI_VERSION__: JSON.stringify(ytPkg.version),
    __BGUTILS_VERSION__: JSON.stringify(bgPkg.version)
  },
  banner: {
    js: `/* Tube bridge bundle ${bundleVersion} — youtubei.js ${ytPkg.version}, bgutils-js ${bgPkg.version}. Generated by js/build.mjs; do not edit. */`
  },
  logLevel: 'info'
});

console.log(`bundle ${bundleVersion} -> ${outfile}`);
