import XCTest
@testable import Core

final class CookieParserTests: XCTestCase {
    let netscape = """
    # Netscape HTTP Cookie File
    # This file is generated by a browser extension.

    .youtube.com\tTRUE\t/\tTRUE\t1790000000\tSID\tsid-value
    .youtube.com\tTRUE\t/\tTRUE\t1790000000\tHSID\thsid
    .youtube.com\tTRUE\t/\tTRUE\t1790000000\tSAPISID\tsap/isid
    #HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1790000000\t__Secure-3PSID\tsecure3p
    .google.com\tTRUE\t/\tTRUE\t1790000000\tNID\tgoogle-only
    www.youtube.com\tFALSE\t/\tFALSE\t0\tPREF\tf6=40000000&tz=Europe.Berlin
    """

    func testNetscape() throws {
        let header = try CookieParser.parse(netscape)
        XCTAssertEqual(header, "SID=sid-value; HSID=hsid; SAPISID=sap/isid; __Secure-3PSID=secure3p; PREF=f6=40000000&tz=Europe.Berlin")
        XCTAssertFalse(header.contains("NID"), "google.com cookies are dropped")
    }

    func testRawHeader() throws {
        let header = try CookieParser.parse("Cookie: SID=a; SAPISID=b ;  LOGIN_INFO=c=d")
        XCTAssertEqual(header, "SID=a; SAPISID=b; LOGIN_INFO=c=d")
    }

    func testJSONExport() throws {
        let json = """
        [{"domain":".youtube.com","name":"__Secure-1PSID","value":"x1"},
         {"domain":".youtube.com","name":"__Secure-3PAPISID","value":"papi"},
         {"domain":"accounts.google.com","name":"LSID","value":"nope"}]
        """
        let header = try CookieParser.parse(json)
        XCTAssertEqual(header, "__Secure-1PSID=x1; __Secure-3PAPISID=papi; SAPISID=papi", "SAPISID synthesized from __Secure-3PAPISID")
    }

    func testErrors() {
        XCTAssertThrowsError(try CookieParser.parse("   ")) { XCTAssertEqual($0 as? CookieParseError, .empty) }
        XCTAssertThrowsError(try CookieParser.parse("hello world")) { XCTAssertEqual($0 as? CookieParseError, .unrecognized) }
        XCTAssertThrowsError(try CookieParser.parse(".google.com\tTRUE\t/\tTRUE\t0\tSID\tx")) {
            XCTAssertEqual($0 as? CookieParseError, .noYouTubeCookies)
        }
        XCTAssertThrowsError(try CookieParser.parse("PREF=1; VISITOR_INFO1_LIVE=2")) {
            XCTAssertEqual($0 as? CookieParseError, .missingAuthCookies)
        }
    }
}

final class HTTPParsingTests: XCTestCase {
    func testCompleteFormPost() {
        let body = "cookies=SID%3Da%3B+SAPISID%3Db&x=1"
        let raw = "POST /cookies HTTP/1.1\r\nHost: 192.168.1.20:8765\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: \(body.utf8.count)\r\n\r\n\(body)"
        guard case .complete(let request, let consumed) = HTTPRequestParser.parse(Data(raw.utf8)) else {
            return XCTFail("expected complete")
        }
        XCTAssertEqual(consumed, raw.utf8.count)
        XCTAssertEqual(request.method, "POST")
        XCTAssertEqual(request.path, "/cookies")
        XCTAssertEqual(request.headers["host"], "192.168.1.20:8765")
        XCTAssertEqual(request.formFields["cookies"], "SID=a; SAPISID=b")
    }

    func testIncompleteUntilBodyArrives() {
        let head = "POST /cookies HTTP/1.1\r\nContent-Length: 10\r\n\r\nabc"
        XCTAssertEqual(HTTPRequestParser.parse(Data(head.utf8)), .incomplete)
        XCTAssertEqual(HTTPRequestParser.parse(Data("GET / HTTP/1.1\r\nHost: x".utf8)), .incomplete)
    }

    func testGetWithQuery() {
        guard case .complete(let request, _) = HTTPRequestParser.parse(Data("GET /status?x=1&y=a+b HTTP/1.1\r\n\r\n".utf8)) else {
            return XCTFail("expected complete")
        }
        XCTAssertEqual(request.path, "/status")
        XCTAssertEqual(request.query, ["x": "1", "y": "a b"])
    }

    func testRejectsChunkedAndHuge() {
        let chunked = "POST / HTTP/1.1\r\nTransfer-Encoding: chunked\r\n\r\n"
        if case .invalid = HTTPRequestParser.parse(Data(chunked.utf8)) {} else { XCTFail("chunked must be rejected") }
        let huge = "POST / HTTP/1.1\r\nContent-Length: 99999999\r\n\r\n"
        if case .invalid = HTTPRequestParser.parse(Data(huge.utf8)) {} else { XCTFail("huge body must be rejected") }
    }

    func testResponseSerialization() {
        let response = HTTPResponse.html("<p>hi</p>")
        let text = String(decoding: response.serialized(), as: UTF8.self)
        XCTAssertTrue(text.hasPrefix("HTTP/1.1 200 OK\r\n"))
        XCTAssertTrue(text.contains("Content-Length: 9\r\n"))
        XCTAssertTrue(text.hasSuffix("\r\n\r\n<p>hi</p>"))
    }

    func testSetupPageEscapes() {
        let html = SetupPage.html(.success(accountName: "<b>Me</b>"))
        XCTAssertTrue(html.contains("&lt;b&gt;Me&lt;/b&gt;"))
        XCTAssertTrue(SetupPage.html(.form(message: nil)).contains("name=\"cookies\""))
    }
}

final class CookieJarTests: XCTestCase {
    func testRotationUpdatesOnlyKnownCookies() {
        var jar = CookieJar(header: "SID=a; __Secure-3PSIDTS=old; SIDCC=x")
        let changed = jar.apply([
            CookieJar.Update(name: "__Secure-3PSIDTS", value: "new", domain: ".youtube.com"),
            CookieJar.Update(name: "BRAND_NEW", value: "1", domain: ".youtube.com"),
            CookieJar.Update(name: "SID", value: "", domain: ".youtube.com"),
            CookieJar.Update(name: "SIDCC", value: "y", domain: ".google.com")
        ])
        XCTAssertTrue(changed)
        XCTAssertEqual(jar.header, "SID=a; __Secure-3PSIDTS=new; SIDCC=x")
    }

    func testIgnoresExpiredAndMaxAgeZero() {
        var jar = CookieJar(header: "A=1; B=2")
        let now = Date(timeIntervalSince1970: 2_000_000_000)
        jar.apply([
            CookieJar.Update(name: "A", value: "9", expires: Date(timeIntervalSince1970: 1_000)),
            CookieJar.Update(name: "B", value: "9", maxAge: 0)
        ], now: now)
        XCTAssertEqual(jar.header, "A=1; B=2")
    }

    func testParseSetCookie() {
        let update = CookieJar.parseSetCookie("__Secure-3PSIDTS=abc=; Domain=.youtube.com; Expires=Wed, 21 Oct 2037 07:28:00 GMT; Path=/; Secure; HttpOnly")
        XCTAssertEqual(update?.name, "__Secure-3PSIDTS")
        XCTAssertEqual(update?.value, "abc=")
        XCTAssertEqual(update?.domain, ".youtube.com")
        XCTAssertNotNil(update?.expires)
        XCTAssertEqual(CookieJar.parseSetCookie("X=1; Max-Age=0")?.maxAge, 0)
    }

    func testParseSetCookieSkipsEmptyAttributes() {
        let update = CookieJar.parseSetCookie("SIDCC=abc; ; Secure; =; =x; Domain=.youtube.com; Max-Age=60; ")
        XCTAssertEqual(update?.name, "SIDCC")
        XCTAssertEqual(update?.value, "abc")
        XCTAssertEqual(update?.domain, ".youtube.com")
        XCTAssertEqual(update?.maxAge, 60)
        XCTAssertNotNil(CookieJar.parseSetCookie("A=1; = "))
        let empty = CookieJar.parseSetCookie("A=1; Domain=; Max-Age=; Expires=")
        XCTAssertNil(empty?.domain)
        XCTAssertNil(empty?.maxAge)
        XCTAssertNil(empty?.expires)
    }
}
